version: '3.8'

services:
  app:
    container_name: spring_app
    image: jiyoon0221/my-spring-app
    restart: always
    ports:
      - "443:443"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - KEY_STORE_PATH=/app/keystore.p12  # keystore.p12 파일 경로
    networks:
      - my_network

networks:
  my_network:
    driver: bridge