version: '3.8'

services:
  app:
    container_name: spring_app
    image: jiyoon0221/my-spring-app
    restart: always
    ports:
      - "443:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - my_network

networks:
  my_network:
    driver: bridge