# 공통 URL 관리
base-url: "http://localhost:8080"  # 배포 시 실제 도메인으로 변경 예정
redirect-url: "http://localhost:8080/swagger-ui/index.html" # 소셜 로그인 성공 후 리다이렉트 되는 주소 -> 프론트 주소로 변경 예정


# 기타 설정
withdrawn:
  delete-time: 60     # 초 단위
  check-time: 30      # 초 단위 ( delete-time 보다 짧게 설정해야 오류가 없음 )

# 포트 설정
server:
  port: 8080


# spring 설정들
spring:
  web:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


  # 기본 시간대 설정 ( 베이스 엔티티에는 미적용 상태 )
  time-zone: Asia/Seoul

  # DB 설정
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: kang0205~!itskkkcake1221ps
    driver-class-name: com.mysql.cj.jdbc.Driver

  # jpa 설정
  jpa:
    hibernate:
      ddl-auto: create # 엔티티 확정 후에는 update 로 변경 예정
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    security:
      enable-csrf: false

  # jwt 설정
  jwt:
    secret: "hadgfsfsfsfsssfsfssfsfsfsffasadad1234567890"
    expiration:
      access-token: 3600  # 1 day
      refresh-token: 604800  # 7 days

  # 소셜 로그인 설정
  security:
    oauth2:
      client:
        google-path-uri: "/authorization/oauth2/code/google"
        kakao-path-uri: "/authorization/oauth2/code/kakao"
        naver-path-uri: "/authorization/oauth2/code/naver"

        registration:
          google:
            client-id: 99902361774-6374rph82cs4mjbjqb1c9evp61pl3h2b.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
            redirect-uri: ${base-url}/authorization/oauth2/code/google

          kakao:
            client-id: 28aafe4adf59867d844dce294b455c6c
            client-secret: JuOWB45mg985VegMqx7bmthrXNEb9l6O
            authorization-grant-type: authorization_code
            redirect-uri: ${base-url}/authorization/oauth2/code/kakao
            scope:
              - account_email
              - profile_nickname
            client-name: Kakao
            client-authentication-method: client_secret_post

          naver:
            client-id: HGFL3G6ki_OOV3XqA8TP
            client-secret: opHypdrNau
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: ${base-url}/authorization/oauth2/code/naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          google:
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo